/* Do not modify this file, it was automatically generated by CMake. */

/*
 * Define the KiCad build version string.
 */
#ifndef __KICAD_VERSION_H__
#define __KICAD_VERSION_H__

#define KICAD_VERSION_FULL "(5.99.0-871-g43be61b7d)"

#endif  /* __KICAD_VERSION_H__ */
