// Generated by the generate_ngspice_model_info.bash script.
// Modify that script instead of this file if you want to make changes.

#include <sim/ngspice.h>

enum class NGSPICE::MODEL_TYPE
{
    NONE,
    RESISTOR,
    CAPACITOR,
    INDUCTOR,
    LTRA,
    TRANLINE,
    URC,
    TRANSLINE,
    DIODE,
    BJT,
    VBIC,
    HICUM2,
    JFET,
    JFET2,
    MES,
    MESA,
    HFET1,
    HFET2,
    MOS1,
    MOS2,
    MOS3,
    BSIM1,
    BSIM2,
    MOS6,
    BSIM3,
    MOS9,
    B4SOI,
    BSIM4,
    B3SOIFD,
    B3SOIDD,
    B3SOIPD,
    HISIM2,
    HISIMHV1,
    HISIMHV2,
};
